name: integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Lint
        run: zig fmt --check .

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Test (${{matrix.mode}})
        run: zig build -Doptimize=${{matrix.mode}} --summary all test
